import { Provider } from "react-redux";
import "./globals.scss";
import { Inter } from "next/font/google";
import { store } from "./Client/Store/store";
import { Providers } from "./Client/Store/Provider/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>
          {children}
          <footer></footer>
        </body>
      </html>
    </Providers>
  );
}
